FROM ruby:3.0.2

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y build-essential nodejs yarn imagemagick libmagick++-dev vim

WORKDIR /app

RUN echo "alias ll='ls -lG'" >> /root/.bashrc

RUN gem install bundler

COPY Gemfile Gemfile.lock package.json yarn.lock /app/

RUN bundle config set path vendor/bundle
RUN bundle install
RUN yarn install

CMD ["bash"]