version: '3'

services:
  app:
    hostname: 'app'
    build:
      context: .
      dockerfile: ./Dockerfile.prd
    command: bundle exec foreman start
    working_dir: /app
    tty: true
    environment:
      RAILS_ENV: ${RAILS_ENV}
      MYSQL_USERNAME: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      TZ: Asia/Tokyo
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - sockets:${PUMA_SOCKET_PATH}
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PORT: ${DB_PORT}
      TZ: Asia/Tokyo
    ports:
      - '${DB_PORT}:${DB_PORT}'
    command: --port ${DB_PORT}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - sockets:${PUMA_SOCKET_PATH}
    depends_on:
      - app
    environment:
      TZ: Asia/Tokyo
      PUMA_SOCKET_PATH: ${PUMA_SOCKET_PATH}
      NGINX_PORT: ${NGINX_PORT}

  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: --port ${REDIS_PORT}
    volumes:
      - "redis-data:/data"
    environment:
      TZ: Asia/Tokyo

volumes:
  mysql-data:
  sockets:
  redis-data:
  bundle:
  node_modules: