FROM nginx:1.21
RUN apt-get update && \
  apt-get install -y apt-utils locales procps netcat iproute2 && \
  echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen && \
  locale-gen ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
RUN echo "alias ll='ls -lG'" >> /root/.bashrc
COPY ./containers/nginx/puma.conf.template /etc/nginx/templates/default.conf.template